bubbleSort,
    // invertArray,
    // invertArrayInplace,
    // capitalize,
    // mcd,
    // hackerSpeak,
    // factorize,
    // deduplicate,
    // findShortestString,
    // isPalindrome,
    // sortStrings,
    // stats,
    // popularString,
    // isPowerOf2,
    // sortDescending,